### PR TITLE
Footer For Page ,Updated Drawer Layout And Loader for Profile 

### LINKED ISSUE #77: Create Footer:
image
Create Footer component

### PR DESCRIPTION
**Pull request by harkiratsm**
Fixes #77
**Footer is all done ✅
New Drawer Layout ✅** 

**Loader for Profile Page**  ✅

_Removed Some Bugs Related to Drawer_

### CODE REVIEW

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 can u tell why all these check failed

**Comment by Abhishek-kumar09** [comment]
You have unused variables in your code, remove them:
image

**Comment by harkiratsm** [comment]
Capture

**Comment by harkiratsm** [comment]
@Abhishek-kumar09

**Comment by Abhishek-kumar09** [comment]
It should have spanned to full length:
image

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 I will correct this issue rest tell about drawer layout

**Review by Abhishek-kumar09 — COMMENTED** [review]
image
Give top and bottom padding to the user profile.
Try to relicate the figma as it is, or as most as possible.

**Comment by harkiratsm** [comment]
Sure I will do it

**Comment by harkiratsm** [comment]
The icon on font awesome which I want to use  are pro so I have to use this one any solution

**Comment by Abhishek-kumar09** [comment]
> The icon on font awesome which I want to use are pro so I have to use this one any solution

We can keep these fontawesome icons for now, Our new/next project will solve the problem you are facing. We will be creating our own custome icons packs that will be hosted on npm, which we could use without importing svgs soon.

For now it is fine.

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 i have other loader animation .You can tell me if this is fine for u

**Comment by Abhishek-kumar09** [comment]
can you share that animation, gif or video of new loader?

**Comment by Abhishek-kumar09** [comment]
Just saw the loader animation, it is not aligning to the theme.

**Review by Abhishek-kumar09 — COMMENTED** [review]
This problem is not solved:
image

**Comment by harkiratsm** [comment]
Ok @Abhishek-kumar09

**Comment by harkiratsm** [comment]
@Abhishek-kumar09  according to figma design  I think this is fine. rest kya meeting rakh le

**Comment by Abhishek-kumar09** [comment]
> @Abhishek-kumar09 according to figma design I think this is fine. rest kya meeting rakh le

Yes it is fine, but there should be no whitespace below. I should span across full width.
https://www.youtube.com/watch?v=g9-UT4vavbw

**Comment by Abhishek-kumar09** [comment]
Can we have different loader animation.the current one is not aligning to the theme

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 ok bro

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 I added a new Loader and Updated the issue regarding to white Space .

**Review by Abhishek-kumar09 — CHANGES_REQUESTED** [review]
I have fixed the homepage alignment issues, please look into drawer part and try to replicate the design.
The selected drawer component should look like this:
image

**Comment by Abhishek-kumar09** [comment]
DOn't forget to do git pull before making your own changes

**Comment by Abhishek-kumar09** [comment]
Hey @harkiratsm Is there any update

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 yeah I am working on it

**Comment by harkiratsm** [comment]
Have u checked the new loader

**Comment by Abhishek-kumar09** [comment]
Yes, I have checked it.That is looking much better. Please apply other suggested changes. This PR includes some crucial changes to be merged.

**Comment by harkiratsm** [comment]
@Abhishek-kumar09 i have added bg on click in drawer layout

**Pull request merged**
