### PR TITLE
Fixed #42 & a small typo

### LINKED ISSUE #42: Bug: Uncaught exception in Calendar.js caused by mapping over nonexistent keys in 'events' object
## Expected Behavior

The dashboard route should display the calendar according to the UI mentioned in #23 

## Actual Behavior

The dashboard page doesn't load, and instead displays the following error while in development mode:
`TypeError: Cannot read property '29' of undefined`

## Steps to Reproduce the Problem

1. Setup and run the application as instructed in the project's README.
2. Go to the dashboard route in your browser *(localhost:3000/dashboard in my case)*.

## Specifications

Describe any relevant information related to issue

- OS: Windows
- Browser: Chrome

**Screenshots**

*Expected output:*
image

*Actual output:*
image

**Additional context**
I've fixed the issue locally and will be making a PR for review.

### PR DESCRIPTION
**Pull request by zeborg**
Also added new dummy events for the month of April in the 'events' object to demonstrate the calendar's working with events in current month (April).

### Related Issue

Fixes #42

### Type of Change:

- Code

**Code/Quality Assurance Only**

- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Tested over local node environment for multiple event dates.

### Checklist:

- [x] Pull request is made against `development` branch.
- [x] My code follows the style guidelines of this project.
- [x] I run `npm run format` before creating the pull request.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings

### Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by mdPial** [comment]
@zeborg 
You don't need to change other lines. Just get the key dynamically otherwise it **will generate error on the next month again**. I had created it for test purposes so I didn't make that dynamic.

Just change line **101**
```diff
+ [now.getMonth()] : {
- 3: {
```

**Comment by piall** [comment]
@zeborg 
You don't need to change and add other lines. Just get the key dynamically otherwise it **will generate an error on the next month again**. I had created it for demo purpose so I forgot to make that dynamic.  :weary: 

Just change the line **101**
```diff
+ [now.getMonth()] : {
- 2: {
```

& thanks for reaching out to me :smile:   and fixing the typo :weary:

**Comment by zeborg** [comment]
> I had created it for demo purpose so I forgot to make that dynamic.  :weary: 

I see! Yeah that actually makes more sense, I thought that although currently for demo purposes, `events` served as the object where the events data would be stored and fetched from after querying the db 😬

I'll add the final commit with your proposed solution. Thanks 🙏

**Comment by Abhishek-kumar09** [comment]
Works well!

**Pull request merged**
