### PR TITLE
Event Form

### PR DESCRIPTION
**Pull request by Amishakumari544**
Created Event Page

### CODE REVIEW

**Comment by zeborg** [comment]
@Amishakumari544 I believe that fixing these issues would prevent your PR from failing the checks.

image

**Comment by Abhishek-kumar09** [comment]
Nice @amikudev,

This is an image picker actually 
image

We will be picking image from  the computer with this button. 
Ref: https://www.npmjs.com/package/react-images-upload

**Comment by Amishakumari544** [comment]
> Nice @amikudev,
> 
> This is an image picker actually
> image
> 
> We will be picking image from the computer with this button.
> Ref: https://www.npmjs.com/package/react-images-upload

ok

**Comment by Abhishek-kumar09** [comment]
@Amishakumari544 You can see how the form is created here for reference: 
https://github.com/codeforcauseorg/causefolio/pull/65/files

**Comment by Amishakumari544** [comment]
> @Amishakumari544 You can see how the form is created here for reference:
> https://github.com/codeforcauseorg/causefolio/pull/65/files

Ok thank you for the reference.

**Pull request merged**
